### PR TITLE
Add option to use data restful endpoint

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Hawkuar versions < 0.13.0 used a `.../data` endpoint, and the `.../raw` did not exist.

This PR allow the use of this client with older versions of Hawkular

### CODE REVIEW

**Comment by yaacov** [comment]
@simon3z @burmanm please review

The Hawkular version QE is using is 0.8.x. That version does not answer to `.../raw` endpoint, making this library compatible with old versions will make it easier for me to work with the machine QE have.

p.s.
@simon3z do we support old hawkulars ?
@burmanm if you do not want to support old versions it's ok, I can use curl when speaking to old hawkulars :-) , just comment here, and I will close this PR.

**Comment by simon3z** [comment]
> @simon3z do we support old hawkulars ?

@yaacov for CM we support up to what was delivered with OpenShift 3.1 (Einat has an env for you to check).

I think that we need this but it should be automatic (not a parameter that gets passed).
Please check also the ruby client.

**Comment by yaacov** [comment]
@simon3z 

> Please check also the ruby client.

ruby  check `/metrics/status ` to get the version before doing `.../raw` or `.../data` .

> I think that we need this but it should be automatic (not a parameter that gets passed).

Automation can be done where we use this client, we can do a call to `/metrics/status ` and then set this parameter according to the version.

**Comment by yaacov** [comment]
@simon3z @burmanm added a `status` method to get the Hawkular server version, this can be used to automate the `raw/data` endpoint usage.

**Comment by yaacov** [comment]
@burmanm we need to support old version of Hawkular, please review.

cc// @simon3z 
p.s.
I do not like the name `use_data_endpoint` do you have a better name ?

**Comment by yaacov** [comment]
@zgalor please review.

**Comment by yaacov** [comment]
> Please check also the ruby client.

@simon3z @burmanm just updated this PR to be like the ruby client:

a. changed the parameter to be lagacy_api (like the ruby client)
b. change the raw and the stats endpoints (like the ruby client)
https://github.com/hawkular/hawkular-client-ruby/blob/master/lib/hawkular/metrics/metric_api.rb#L218

**Comment by simon3z** [comment]
I don't think that the understanding of `lagacy_api` should be in the lib user. Do you really want every user to be familiar with the nits of the API, versions, etc?

The user just wants the data.

**Comment by pilhuhn** [comment]
I totally agree with @simon3z on https://github.com/hawkular/hawkular-client-python/pull/20#issuecomment-264852317 This is not too hard to decide depending on the api version returned by the /status endpoint

**Comment by zgalor** [comment]
@yaacov I don't see the point in passing a param for a logic that's known within the hawk-client. This can only result in errors, and gives no added value to the user.

Better if the hawk-client redirects to relevant url based on version, as in ruby client:
https://github.com/hawkular/hawkular-client-ruby/blob/08dfdc8ee23d3ff0eded32910b7bee1d80536a0b/lib/hawkular/metrics/metrics_client.rb#L43

**Comment by yaacov** [comment]
> I don't think that the understanding of lagacy_api should be in the lib user

@simon3z @pilhuhn @zgalor ok :sunglasses:
a. added an automatic check
b. will add tests tomorrow

**Comment by yaacov** [comment]
@burmanm how do i run the tests ? i need a hawkular server on localhost:8080 ?

**Comment by yaacov** [comment]
@burmanm please review

p.s.
I do not know how to run the tests :-(

**Comment by yaacov** [comment]
@simon3z @pilhuhn @burmanm please review

Added tests, all tests pass

**Pull request merged**
