### PR TITLE
Setting up Travis CI 

### PR DESCRIPTION
**Pull request by rubenvp8510**

### CODE REVIEW

**Comment by yaacov** [comment]
👍 For fixing the string metrics test

Can you set to test with more then one hawkular version ?
We have a PR to support legacy API #20 and It will be nice if legacy versions also get tested.

**Comment by burmanm** [comment]
Can you rebase?

**Comment by yaacov** [comment]
Thanks 👍

**Comment by rubenvp8510** [comment]
@burmanm This is ready for another review could you please review it when you get a chance? Thank you!, @yaacov I added tests for version 0.15, I'm not sure if that is enough.

**Comment by yaacov** [comment]
@rubenvp8510 it's just what I wanted ( ver < 0.16 ) 

p.s.
I wanted this because the QE team is now using very old 0.8, I hope they will start using 0.21 soon, with the alerts, and I will not need this :-)

**Pull request merged**
